### ISSUE TITLE
Documented action of plotTensor3D

### ISSUE THREAD

**Issue by Stat-Cook** [rikenbit/nnTensor#1] opened 2022-12-15 16:03 UTC
[Lovely package by the way - please excuse if these comments read as highly kurt I'm trying to be concise]

The use of plotTensor3D given in the JOSS paper does not reproduce on my system - instead get a semi blank image.  May be other dependencies needed.

![image](https://user-images.githubusercontent.com/51404549/207908982-d4036e9a-96ab-4591-9204-6d7992af272c.png)

**Comment by kokitsuyuzaki** [comment] 2022-12-16 03:32
Could you send the message generated by `sessionInfo()` in R console?

**Comment by kokitsuyuzaki** [comment] 2022-12-23 06:21
I couldn't reproduce your situation in my environment.
I checked the function on Mac desktop and Linux (CentOS) server but the plot is properly generated.

The function is tested here,
https://github.com/rikenbit/nnTensor/blob/db7feffb1e8618ad327d210ffda4a3a6b41957b0/tests/testthat.R#L16
and at least the figure is properly generated on 13 machines.
https://cran.rstudio.com/web/checks/check_results_nnTensor.html

**Comment by kokitsuyuzaki** [comment] 2022-12-23 06:25
Perhaps, is it related to XQuartz (https://www.xquartz.org)?

If you have not already, could you install XQuartz on your machine and draw the figure again?
https://cran.r-project.org/web/packages/nat/vignettes/Installation.html

**Comment by kokitsuyuzaki** [comment] 2023-02-15 13:59
I found that this error occurs when plotting with R-Studio.

![スクリーンショット 2023-02-15 16 00 02](https://user-images.githubusercontent.com/2173745/219047442-55dd09ee-0fdc-4c99-b471-2f2e7094bfc6.png)

The cause was that when plotting with plot3D::scatter3D, the area where 0 is specified in col becomes transparent in R.app or R in CLI but in R-Studio, it seems to be drawn as white for some reason.
Now I was able to reproduce the Figure in the JOSS paper in R-Studio by explicitly specifying a color with transparency.
In my environment, this bug was resolved in nnTensor (v-1.1.12), so please try in that environment.
If the bug cannot resolved, please open the Issue again.

**Closed as completed by kokitsuyuzaki** 2023-02-15 13:59 UTC
